# 参考自以下教程 https://juejin.im/post/6844903517853843470
# PS：发现自己除了JAVA和类C语言以外好像啥都不会，太惨了，得多学习了
# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# node js 版本
node_js:
  - lts/*

# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

# 指定博客源码分支，因人而异。hexo博客源码托管在独立repo则不用设置此项
branches:
  only:
    - source_code 

before_install:
  - export TZ='Asia/Shanghai'

# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-cli -g
  - npm install hexo-generator-searchdb --save

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - git config user.name "wyhgoodjob"
  - git config user.email "wyhgoodjob@gmail.com"
  # 替换同目录下的_config.yml文件中github_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/github_token/${Github_IO_Token}/g" ./_config.yml
  - hexo deploy
# End: Build LifeCycle